token:
  expiration_time: 86400001
  secret: user_token_native_user_service

gateway:
  ip: 127.0.0.1

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ecommerce
    driver-class-name: org.mariadb.jdbc.Driver
    username: '{cipher}AQAT4OiDV3vAmZIYpMiItR3EnX6cY15ofsEHiM5K+x1ln5qJbxAYl57oyvNGnVyL7tXo/X5MloOFJ4yxJXYlwutdXExJX3u5Sc0pFYSBcL6N7naozIDknz92QPtYVAf+A+cpPex3PG6Alqbrp/tWEyPEJZSa5qgIio8yDE8pfvKiIbAWjytwFUxQX9RwlDJfEBiSj1gaF2oh9xwPNMMq3gzqi1hSN9Pda718Hw4fiYBvOT8AeUvu8ZESR0DDhOyQCqNEiBb+K/U1PPT/aIo508vIW6mJwVW1Z4sEci81j/YtqGIIZb3gsqmtADavZhmc0yAIK4z5iv3y+R6utsxn1Z9ADPAGvcCy1k9iUM2ngckxXEGktwlgBUlG8CkLU7DmsPI='
    password: '{cipher}AQAt55WBWlyfJkHaojuq6EpHooyTxbU43CRFN7vWtxSfG8ljh/bejB4KEvfeaJ9f/KyD7JMNja5WOL4Bw+HkHop4ylaZxZqkMlNHDquiySv7jxCqKKHkEqnxG3ZE793v0SwWkQAzADEDHUaKyHBDn9998gH2MkjBwe45yCPhd5wva9z/57/Um6AZjQ5uXmM104SDXacivsx3T29t/XSD3ske4bPu1ZpZUY1iqd8LVzmtCbJ3ZQCb8+6qKEIj+VjEcVHmoYN8BGqlsxTGawVk9FOI1jDUt8q0V/4d82xhPuRqohxxL+ZHN5MzhOecrfWnqxMXk5rDf7x5bVFQiw7mvTkz/VPXvoA6xf5Dq3rYYSnRYBGKTWkA83zw2/UEdw9fd6Y='
